name: CD - Deploy to Railway and GitHub Pages

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # === RAILWAY DEPLOYMENT ===
    - name: Deploy to Railway
      run: |
        curl -X POST ${{ secrets.RAILWAY_DEPLOY_HOOK }}

    # === GITHUB PAGES DEPLOYMENT ===
    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./  # Or specify your content folder if needed

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
