name: CD - Deploy to GitHub Pages

on:
  push:
    tags:
      - 'v*'   # Deploy only when you push a version tag like v1.0

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./  # Upload everything (or specify your content folder if needed)

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
