name: CD - Test and Deploy to GitHub Pages

on:
  push:
    tags:
      - 'v*'   # Deploy only on version tags like v1.0

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest  # Add pytest for testing

    - name: Run Tests
      run: pytest tests/  # Runs your tests

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./  # Upload everything (or specify your content folder if needed)

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
